<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.9 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/TrackElements/Barriers/BarrierEnd/BarrierEnd.glb -u -i -t -s
-->
<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'
	import { Collider } from '@threlte/rapier'
	import { useRefreshCollider } from '../../utils/useRefreshCollider'

	export const ref = new Group()

	const suspend = useSuspense()

	type GLTFResult = {
		nodes: {
			BarrierEnd: THREE.Mesh
		}
		materials: {}
	}

	const gltf = suspend(useGltf<GLTFResult>('/BarrierEnd.glb'))

	const { refreshFns } = useRefreshCollider()
</script>

<T is={ref} dispose={false}>
	<T.Group position.y={0.3}>
		<Collider shape="cylinder" args={[0.3, 0.5]} type="static" bind:refresh={refreshFns[0]} />
	</T.Group>

	{#if $gltf}
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.BarrierEnd.geometry}
			material={$gltf.nodes.BarrierEnd.material}
		>
			<slot name="selection" />
		</T.Mesh>
	{/if}

	<slot {ref} />
</T>
