<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.9 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/TrackElements/Ramps/RampInverse/RampInverse.glb -u -i -t -s
-->
<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'
	import MeshCollider from '../../utils/components/MeshCollider.svelte'

	export const ref = new Group()

	const suspend = useSuspense()

	type GLTFResult = {
		nodes: {
			RampInverse: THREE.Mesh
		}
		materials: {
			Ramps: THREE.MeshStandardMaterial
		}
	}

	const gltf = suspend(useGltf<GLTFResult>('/RampInverse.glb'))
</script>

<T is={ref} dispose={false}>
	{#if $gltf}
		<MeshCollider>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.RampInverse.geometry}
				material={$gltf.materials.Ramps}
				rotation={[Math.PI / 2, 0, 0]}
			>
				<slot name="selection" />
			</T.Mesh>
		</MeshCollider>
	{/if}

	<slot {ref} />
</T>
