<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.9 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/Car/Models/MuscleCarGhostWheel.glb -u -i -t -s
-->
<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'

	export const ref = new Group()

	export let opacity: number

	type GLTFResult = {
		nodes: {
			Cube001: THREE.Mesh
		}
		materials: {
			['Material.003']: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/MuscleCarGhostWheel.glb')
</script>

<T is={ref} dispose={false}>
	{#if $gltf}
		<T.Mesh geometry={$gltf.nodes.Cube001.geometry} scale={0.37}>
			<T is={$gltf.materials['Material.003']} {opacity} />
		</T.Mesh>
	{/if}

	<slot {ref} />
</T>
