<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.9 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/Car/Models/MuscleCarGhost.glb -u -i -t -s
-->
<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'

	export const ref = new Group()
	export let opacity: number

	type GLTFResult = {
		nodes: {
			Cube: THREE.Mesh
		}
		materials: {
			['Material.010']: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/MuscleCarGhost.glb')
</script>

<T is={ref} dispose={false}>
	{#if $gltf}
		<T.Mesh castShadow receiveShadow geometry={$gltf.nodes.Cube.geometry} scale={[0.37, 0.31, 2.2]}>
			<T is={$gltf.materials['Material.010']} {opacity} />
		</T.Mesh>
	{/if}

	<slot {ref} />
</T>
