<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.9 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/Car/Models/muscle-car.glb -u -i -t -s
-->
<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'
	import type { CarState } from '../RaycastVehicleController/types'

	export let carState: CarState

	const { isBraking } = carState

	export const ref = new Group()

	const suspend = useSuspense()

	type GLTFResult = {
		nodes: {
			Cube_1: THREE.Mesh
			Cube_2: THREE.Mesh
			Cube_3: THREE.Mesh
			Cube_4: THREE.Mesh
			Cube_5: THREE.Mesh
			Cube_6: THREE.Mesh
			Cube_7: THREE.Mesh
			Cube_8: THREE.Mesh
		}
		materials: {
			Material: THREE.MeshStandardMaterial
			['Material.001']: THREE.MeshStandardMaterial
			['Material.003']: THREE.MeshStandardMaterial
			['Material.004']: THREE.MeshStandardMaterial
			['Material.005']: THREE.MeshStandardMaterial
			['Material.006']: THREE.MeshStandardMaterial
			['Material.007']: THREE.MeshStandardMaterial
			['Material.008']: THREE.MeshStandardMaterial
		}
	}

	const gltf = suspend(useGltf<GLTFResult>('/muscle-car.glb'))
</script>

<T is={ref} dispose={false}>
	{#if $gltf}
		<T.Group scale={[0.37, 0.31, 2.2]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube_1.geometry}
				material={$gltf.materials.Material}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube_2.geometry}
				material={$gltf.materials['Material.001']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube_3.geometry}
				material={$gltf.materials['Material.003']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube_4.geometry}
				material={$gltf.materials['Material.004']}
				material.emissive={$isBraking ? '#ff0000' : '#7E2727'}
				material.envMapIntensity={0}
				material.emissiveIntensity={1}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube_5.geometry}
				material={$gltf.materials['Material.005']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube_6.geometry}
				material={$gltf.materials['Material.006']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube_7.geometry}
				material={$gltf.materials['Material.007']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube_8.geometry}
				material={$gltf.materials['Material.008']}
			/>
		</T.Group>
	{/if}

	<slot {ref} />
</T>
