<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.9 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/Car/Models/muscle-car-wheel.glb -u -i -t -s
-->
<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'

	export const ref = new Group()

	const suspend = useSuspense()

	type GLTFResult = {
		nodes: {
			Cube002: THREE.Mesh
			Cube002_1: THREE.Mesh
			Cube002_2: THREE.Mesh
		}
		materials: {
			['Material.001']: THREE.MeshStandardMaterial
			['Material.002']: THREE.MeshStandardMaterial
			['Material.007']: THREE.MeshStandardMaterial
		}
	}

	const gltf = suspend(useGltf<GLTFResult>('/muscle-car-wheel.glb'))
</script>

<T is={ref} dispose={false}>
	{#if $gltf}
		<T.Group scale={0.37}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube002.geometry}
				material={$gltf.materials['Material.001']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube002_1.geometry}
				material={$gltf.materials['Material.002']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube002_2.geometry}
				material={$gltf.materials['Material.007']}
			/>
		</T.Group>
	{/if}

	<slot {ref} />
</T>
