<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./muscle-car-wheel.glb -i -P -t -s -T
-->
<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'

	type GLTFResult = {
		nodes: {
			Cube002: THREE.Mesh
			Cube002_1: THREE.Mesh
			Cube002_2: THREE.Mesh
		}
		materials: {
			['Material.001']: THREE.MeshStandardMaterial
			['Material.002']: THREE.MeshStandardMaterial
			['Material.007']: THREE.MeshStandardMaterial
		}
	}

	export const ref = new Group()

	const suspend = useSuspense()

	const gltf = suspend(useGltf<GLTFResult>('/muscle-car-wheel-transformed.glb', { useDraco: true }))
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<T.Group scale={0.37}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube002.geometry}
				material={$gltf.materials['Material.001']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube002_1.geometry}
				material={$gltf.materials['Material.002']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Cube002_2.geometry}
				material={$gltf.materials['Material.007']}
			/>
		</T.Group>

		<slot {ref} />
	</T>
{/if}
