<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/TrackElements/HalfUnitBox/HalfUnitBox.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	type GLTFResult = {
		nodes: {
			Floor001: THREE.Mesh
			Floor001_1: THREE.Mesh
		}
		materials: {
			['Metallic Blue']: THREE.MeshStandardMaterial
			['Gray Concretelike']: THREE.MeshStandardMaterial
		}
	}

	const load = () => {
		return useGltf<GLTFResult>('/HalfUnitBox-transformed.glb', { useDraco: true })
	}

	export const preloadHalfunitbox = async () => {
		await load()
	}
</script>

<script lang="ts">
	import { Collider } from '@threlte/rapier'
	import { useRefreshCollider } from '../utils/useRefreshCollider'

	export const ref = new Group()

	const gltf = load()

	const { refreshFns } = useRefreshCollider()
</script>

{#if $gltf}
	<T.Group position.y={-0.25}>
		<Collider bind:refresh={refreshFns[0]} shape="cuboid" args={[5, 0.25, 5]} />
	</T.Group>
	<T is={ref} dispose={false}>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.Floor001.geometry}
			material={$gltf.materials['Metallic Blue']}
		/>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.Floor001_1.geometry}
			material={$gltf.materials['Gray Concretelike']}
		/>
	</T>
{/if}
