FROM node:18-alpine
WORKDIR /app

# Add Env variables
ARG PUBLIC_NAKAMA_HOST
ARG PUBLIC_NAKAMA_PORT
ARG PUBLIC_NAKAMA_SERVER_KEY
ARG PUBLIC_NAKAMA_USE_SSL
ARG PUBLIC_GOOGLE_CLIENT_ID

ENV PUBLIC_NAKAMA_HOST=$PUBLIC_NAKAMA_HOST
ENV PUBLIC_NAKAMA_PORT=$PUBLIC_NAKAMA_PORT
ENV PUBLIC_NAKAMA_SERVER_KEY=$PUBLIC_NAKAMA_SERVER_KEY
ENV PUBLIC_NAKAMA_USE_SSL=$PUBLIC_NAKAMA_USE_SSL
ENV PUBLIC_GOOGLE_CLIENT_ID=$PUBLIC_GOOGLE_CLIENT_ID

RUN npm install -g pnpm

COPY package*.json ./
RUN pnpm i

COPY . .
RUN pnpm run build

WORKDIR /app/build

ENTRYPOINT node index.js

EXPOSE 3000