<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./TiltTransitionLeftLong.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { AutoColliders } from '@threlte/rapier'
	import { useRefreshCollider } from '../../../utils/useRefreshCollider'

	type GLTFResult = {
		nodes: {
			TiltTransitionLeftLong: THREE.Mesh
		}
		materials: {
			['Ramps.003']: THREE.MeshStandardMaterial
		}
	}

	const load = () => {
		return useGltf<GLTFResult>('/TiltTransitionLeftLong-transformed.glb', { useDraco: true })
	}

	export const preloadTilttransitionleftlong = async () => {
		await load()
	}
</script>

<script lang="ts">
	import MeshCollider from '../../../utils/components/MeshCollider.svelte'

	export const ref = new Group()

	const gltf = load()
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<MeshCollider>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.TiltTransitionLeftLong.geometry}
				material={$gltf.materials['Ramps.003']}
			>
				<slot name="selection" />
			</T.Mesh>
		</MeshCollider>

		<slot {ref} />
	</T>
{/if}
