<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/TrackElements/Checkpoint/Checkpoint.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import { T, useFrame } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { Collider, CollisionGroups } from '@threlte/rapier'
	import { derived } from 'svelte/store'
	import type * as THREE from 'three'
	import type { Mesh } from 'three'
	import { Group } from 'three'
	import { useTrackElement } from '../../TrackViewer/TrackElement.svelte'
	import { useTrackViewer } from '../../TrackViewer/TrackViewer.svelte'
	import { useRefreshCollider } from '../utils/useRefreshCollider'
	import { useAudioProvider } from '../../Utilities/AudioProvider.svelte'

	type GLTFResult = {
		nodes: {
			CheckpointTopSign: THREE.Mesh
			CheckpointTopTopPlate: THREE.Mesh
			CheckpointTopTopPlate001: THREE.Mesh
			Floor001: THREE.Mesh
			Floor001_1: THREE.Mesh
		}
		materials: {
			Material: THREE.MeshStandardMaterial
			CheckpointTopMaterial: THREE.MeshStandardMaterial
			['Metallic Blue']: THREE.MeshStandardMaterial
			['Gray Concretelike']: THREE.MeshStandardMaterial
		}
	}

	const load = () => {
		return useGltf<GLTFResult>('/checkpoint-transformed.glb', { useDraco: true })
	}

	export const preloadCheckpoint = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()

	const { checkpointReached, checkpointsReached } = useTrackViewer()
	const trackElement = useTrackElement()

	const currentCheckpointReached = derived(checkpointsReached, (checkpointsReached) => {
		return trackElement && checkpointsReached.has(trackElement.id)
	})

	let signMesh: Mesh

	$: signMaterial = $gltf?.materials.Material.clone()

	useFrame((_, delta) => {
		if (!signMesh) return
		signMesh.rotation.y -= delta * 0.5
	})

	const { refreshFns } = useRefreshCollider()
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<T.Group position={[0, -0.25, 0]}>
			<Collider shape="cuboid" args={[5, 0.25, 5]} />
		</T.Group>

		<T.Group position={[0, 5, 0]}>
			{#if signMaterial}
				<T.Mesh
					castShadow
					receiveShadow
					geometry={$gltf.nodes.CheckpointTopSign.geometry}
					material={signMaterial}
					position={[0, -0.38, 0]}
					material.color="#606060"
					material.roughness={0.3}
					material.metalness={0.3}
					material.emissive={$currentCheckpointReached ? 'green' : '#dc2626'}
					bind:ref={signMesh}
				>
					<Collider
						shape="cylinder"
						args={[0.35, 2.5]}
						type="static"
						bind:refresh={refreshFns[1]}
					/>
				</T.Mesh>
			{/if}
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.CheckpointTopTopPlate.geometry}
				material={$gltf.materials.CheckpointTopMaterial}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.CheckpointTopTopPlate001.geometry}
				material={$gltf.materials.CheckpointTopMaterial}
				position={[0, -0.62, 0]}
				scale={[0.96, 1, 0.96]}
			/>
		</T.Group>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.Floor001.geometry}
			material={$gltf.materials['Metallic Blue']}
		>
			<slot name="selection" />
		</T.Mesh>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.Floor001_1.geometry}
			material={$gltf.materials['Gray Concretelike']}
		>
			<slot name="selection" />
		</T.Mesh>

		<T.Group position.y={2.5}>
			<CollisionGroups groups={[3]}>
				<Collider
					type="static"
					shape="cuboid"
					args={[4.9, 2.4, 4.9]}
					bind:refresh={refreshFns[2]}
					on:sensorenter={() => {
						if (!trackElement) return
						checkpointReached(trackElement.id)
					}}
					sensor
				/>
			</CollisionGroups>
		</T.Group>
	</T>
{/if}
