<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./halfbox.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import type * as THREE from 'three'
	import { Group } from 'three'

	type GLTFResult = {
		nodes: {
			HalfBox: THREE.Mesh
		}
		materials: {
			HalfBox: THREE.MeshStandardMaterial
		}
	}

	const load = () => {
		return useGltf<GLTFResult>('/halfbox-transformed.glb', {
			useDraco: true
		})
	}

	export const preloadHalfbox = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.HalfBox.geometry}
			material={$gltf.materials.HalfBox}
		/>
	</T>
{/if}
