<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.9 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/TrackElements/Boosts/Boost/boost.glb -u -i -t -s
-->
<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, useFrame } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'
	import { Collider, CollisionGroups } from '@threlte/rapier'
	import { useRefreshCollider } from '../../utils/useRefreshCollider'
	import type { RigidBody } from '@dimforge/rapier3d-compat'
	import { Quaternion } from 'three'
	import { Vector3 } from 'three'

	export const ref = new Group()

	const suspend = useSuspense()

	type GLTFResult = {
		nodes: {
			BoostBottom: THREE.Mesh
			BoostTop: THREE.Mesh
		}
		materials: {
			BoostBottom: THREE.MeshStandardMaterial
			BoostTop: THREE.MeshStandardMaterial
		}
	}

	const gltf = suspend(useGltf<GLTFResult>('/boost.glb'))

	const { refreshFns } = useRefreshCollider()

	const rigidBodies: Set<RigidBody> = new Set()

	const addRigidBody = (rigidBody: RigidBody) => {
		rigidBodies.add(rigidBody)
	}

	const removeRigidBody = (rigidBody: RigidBody) => {
		rigidBodies.delete(rigidBody)
	}

	const worldQuaternion = new Quaternion()
	const impulse = new Vector3()

	useFrame(() => {
		if (!rigidBodies.size) return

		ref.getWorldQuaternion(worldQuaternion)

		rigidBodies.forEach((rigidBody) => {
			impulse.set(-1, 0, 0)
			impulse.applyQuaternion(worldQuaternion)
			impulse.multiplyScalar(900)
			rigidBody.applyImpulse(impulse, true)
		})
	})
</script>

<T is={ref} dispose={false}>
	<T.Group position.y={-2.5}>
		<Collider shape="cuboid" args={[5, 2.5, 5]} type="static" bind:refresh={refreshFns[0]} />
	</T.Group>
	<T.Group position.y={0.2}>
		<CollisionGroups groups={[3]}>
			<Collider
				shape="cuboid"
				args={[5, 0.2, 5]}
				type="static"
				bind:refresh={refreshFns[1]}
				sensor
				on:sensorenter={({ targetRigidBody }) => {
					if (targetRigidBody) {
						addRigidBody(targetRigidBody)
					}
				}}
				on:sensorexit={({ targetRigidBody }) => {
					if (targetRigidBody) {
						removeRigidBody(targetRigidBody)
					}
				}}
			/>
		</CollisionGroups>
	</T.Group>

	{#if $gltf}
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.BoostBottom.geometry}
			material={$gltf.materials.BoostBottom}
		>
			<slot name="selection" />
		</T.Mesh>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.BoostTop.geometry}
			material={$gltf.materials.BoostTop}
		>
			<slot name="selection" />
		</T.Mesh>
	{/if}

	<slot {ref} />
</T>
