<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./barrier-end.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { Collider } from '@threlte/rapier'
	import { useRefreshCollider } from './utils/useRefreshCollider'

	type GLTFResult = {
		nodes: {
			BarrierEnd: THREE.Mesh
		}
		materials: {}
	}

	const load = () => {
		return useGltf<GLTFResult>('/barrier-end-transformed.glb', {
			useDraco: true
		})
	}

	export const preloadBarrierEnd = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()

	const { refreshFns } = useRefreshCollider()
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<T.Group position.y={0.3}>
			<Collider shape="cylinder" args={[0.3, 0.5]} type="static" bind:refresh={refreshFns[0]} />
		</T.Group>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.BarrierEnd.geometry}
			material={$gltf.nodes.BarrierEnd.material}
		>
			<slot name="selection" />
		</T.Mesh>

		<slot {ref} />
	</T>
{/if}
