<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./barrier.glb -i -P -t -s -T
-->
<script lang="ts" context="module">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { Collider } from '@threlte/rapier'
	import { useRefreshCollider } from './utils/useRefreshCollider'

	type GLTFResult = {
		nodes: {
			Barrier: THREE.Mesh
		}
		materials: {}
	}

	const load = () => {
		return useGltf<GLTFResult>('/barrier-transformed.glb', {
			useDraco: true
		})
	}

	export const preloadBarrier = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()

	const { refreshFns } = useRefreshCollider()
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<T.Group position.y={0.3} position.z={-4.75}>
			<Collider shape="cuboid" args={[5, 0.3, 0.3]} type="static" bind:refresh={refreshFns[0]} />
		</T.Group>

		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.Barrier.geometry}
			material={$gltf.nodes.Barrier.material}
		>
			<slot name="selection" />
		</T.Mesh>

		<slot {ref} />
	</T>
{/if}
