<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./barrier-turn-left.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { AutoColliders } from '@threlte/rapier'
	import { useRefreshCollider } from './utils/useRefreshCollider'

	type GLTFResult = {
		nodes: {
			BarrierTurnLeft: THREE.Mesh
		}
		materials: {}
	}

	const load = () => {
		return useGltf<GLTFResult>('/barrier-turn-left-transformed.glb', { useDraco: true })
	}

	export const preloadBarrierTurnRight = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()

	const { refreshFns } = useRefreshCollider()
</script>

{#if $gltf}
	<T is={ref} dispose={false} scale.x={-1}>
		<AutoColliders shape="trimesh" bind:refresh={refreshFns[0]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.BarrierTurnLeft.geometry}
				material={$gltf.nodes.BarrierTurnLeft.material}
			>
				<slot name="selection" />
			</T.Mesh>
		</AutoColliders>

		<slot {ref} />
	</T>
{/if}
