<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./boost.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import type * as THREE from 'three'
	import { Group, Quaternion, Vector3 } from 'three'
	import { T, useFrame } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { useRefreshCollider } from './utils/useRefreshCollider'
	import { Collider, CollisionGroups } from '@threlte/rapier'
	import type { RigidBody } from '@dimforge/rapier3d-compat'

	type GLTFResult = {
		nodes: {
			BoostBottom: THREE.Mesh
			BoostTop: THREE.Mesh
		}
		materials: {
			BoostBottom: THREE.MeshStandardMaterial
			BoostTop: THREE.MeshStandardMaterial
		}
	}

	const load = () => {
		return useGltf<GLTFResult>('/boost-transformed.glb', {
			useDraco: true
		})
	}

	export const preloadBoost = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()

	const { refreshFns } = useRefreshCollider()

	const rigidBodies: Set<RigidBody> = new Set()

	const addRigidBody = (rigidBody: RigidBody) => {
		rigidBodies.add(rigidBody)
	}

	const removeRigidBody = (rigidBody: RigidBody) => {
		rigidBodies.delete(rigidBody)
	}

	const worldQuaternion = new Quaternion()
	const impulse = new Vector3()

	useFrame(() => {
		if (!rigidBodies.size) return

		ref.getWorldQuaternion(worldQuaternion)

		rigidBodies.forEach((rigidBody) => {
			impulse.set(-1, 0, 0)
			impulse.applyQuaternion(worldQuaternion)
			impulse.multiplyScalar(1100)
			rigidBody.applyImpulse(impulse, true)
		})
	})
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<T.Group position.y={-2.5}>
			<Collider shape="cuboid" args={[5, 2.5, 5]} type="static" bind:refresh={refreshFns[0]} />
		</T.Group>

		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.BoostBottom.geometry}
			material={$gltf.materials.BoostBottom}
		>
			<slot name="selection" />
		</T.Mesh>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.BoostTop.geometry}
			material={$gltf.materials.BoostTop}
		>
			<slot name="selection" />
		</T.Mesh>

		<T.Group position.y={0.2}>
			<CollisionGroups groups={[3]}>
				<Collider
					shape="cuboid"
					args={[5, 0.2, 5]}
					type="static"
					bind:refresh={refreshFns[1]}
					sensor
					on:sensorenter={({ targetRigidBody }) => {
						if (targetRigidBody) {
							addRigidBody(targetRigidBody)
						}
					}}
					on:sensorexit={({ targetRigidBody }) => {
						if (targetRigidBody) {
							removeRigidBody(targetRigidBody)
						}
					}}
				/>
			</CollisionGroups>
		</T.Group>

		<slot {ref} />
	</T>
{/if}
