<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./checkpoint.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import { T, useFrame } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { Collider, CollisionGroups } from '@threlte/rapier'
	import { derived } from 'svelte/store'
	import type * as THREE from 'three'
	import { Group, Mesh } from 'three'
	import { useTrackElement } from '../TrackViewer/TrackElement.svelte'
	import { useRefreshCollider } from './utils/useRefreshCollider'
	import { actions, gameState } from '$stores/app'

	type GLTFResult = {
		nodes: {
			CheckpointTopSign: THREE.Mesh
			CheckpointTopTopPlate: THREE.Mesh
			CheckpointTopTopPlate001: THREE.Mesh
			CheckpointBase: THREE.Mesh
		}
		materials: {
			Material: THREE.MeshStandardMaterial
			HalfBox: THREE.MeshStandardMaterial
		}
	}

	const load = () => {
		return useGltf<GLTFResult>('/checkpoint-transformed.glb', {
			useDraco: true
		})
	}

	export const preloadCheckpoint = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()

	const { paused, common } = gameState
	const { checkpointsReached } = common

	const trackElement = useTrackElement()

	const checkpointReached = derived(checkpointsReached, (checkpointsReached) => {
		return trackElement && checkpointsReached.has(trackElement.id)
	})

	let signMesh: Mesh

	$: signMaterial = $gltf?.materials.Material.clone()

	const { start, stop } = useFrame(() => {
		if (!signMesh) return
		signMesh.rotation.y -= 0.007
	})

	$: if ($paused) {
		stop()
	} else {
		start()
	}

	const { refreshFns } = useRefreshCollider()
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<T.Group position.y={-2.5}>
			<Collider shape="cuboid" args={[5, 2.5, 5]} type="static" bind:refresh={refreshFns[0]} />
		</T.Group>

		<T.Group position={[0, 5, 0]}>
			{#if signMaterial}
				<T.Mesh
					castShadow
					receiveShadow
					geometry={$gltf.nodes.CheckpointTopSign.geometry}
					material={signMaterial}
					position={[0, -0.38, 0]}
					material.color="#606060"
					material.roughness={0.3}
					material.metalness={0.3}
					material.emissive={$checkpointReached ? 'green' : 'red'}
					bind:ref={signMesh}
				>
					<Collider
						shape="cylinder"
						args={[0.35, 2.5]}
						type="static"
						bind:refresh={refreshFns[1]}
					/>
				</T.Mesh>
			{/if}
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.CheckpointTopTopPlate.geometry}
				material={$gltf.materials.HalfBox}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.CheckpointTopTopPlate001.geometry}
				material={$gltf.materials.HalfBox}
				position={[0, -0.62, 0]}
				scale={[0.96, 1, 0.96]}
			/>
		</T.Group>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.CheckpointBase.geometry}
			material={$gltf.materials.HalfBox}
		>
			<slot name="selection" />
		</T.Mesh>

		<slot {ref} />

		<T.Group position.y={2.5}>
			<CollisionGroups groups={[3]}>
				<Collider
					type="static"
					shape="cuboid"
					args={[5, 2.5, 5]}
					bind:refresh={refreshFns[2]}
					on:sensorenter={() => {
						if (!trackElement) return
						actions.checkpointReached(trackElement.id)
					}}
					sensor
				/>
			</CollisionGroups>
		</T.Group>
	</T>
{/if}
