<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./slope.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { AutoColliders } from '@threlte/rapier'
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { useRefreshCollider } from './utils/useRefreshCollider'

	type GLTFResult = {
		nodes: {
			Slope: THREE.Mesh
		}
		materials: {
			Ramps: THREE.MeshStandardMaterial
		}
	}

	const load = () => {
		return useGltf<GLTFResult>('/slope-transformed.glb', {
			useDraco: true
		})
	}

	export const preloadSlope = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()

	const { refreshFns } = useRefreshCollider()
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<AutoColliders shape="convexHull" bind:refresh={refreshFns[0]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Slope.geometry}
				material={$gltf.materials.Ramps}
				scale={5}
			>
				<slot name="selection" />
			</T.Mesh>
		</AutoColliders>

		<slot {ref} />
	</T>
{/if}
