<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/TrackElements/Finish/Finish.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import { T, useFrame } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { AutoColliders, Collider, CollisionGroups } from '@threlte/rapier'
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { useTrackViewer } from '../../TrackViewer/TrackViewer.svelte'

	type GLTFResult = {
		nodes: {
			Floor_1: THREE.Mesh
			Floor_2: THREE.Mesh
			Holds: THREE.Mesh
			Roof: THREE.Mesh
			RoofBase: THREE.Mesh
			Sign_1: THREE.Mesh
			Sign_2: THREE.Mesh
			Stands: THREE.Mesh
			StandsBase: THREE.Mesh
		}
		materials: {
			['Metallic Blue']: THREE.MeshStandardMaterial
			['Gray Concretelike']: THREE.MeshStandardMaterial
			Metall: THREE.MeshStandardMaterial
			FinishSign: THREE.MeshStandardMaterial
			['Metallic Dark']: THREE.MeshStandardMaterial
		}
	}

	const load = () => {
		return useGltf<GLTFResult>('/Finish-transformed.glb', { useDraco: true })
	}

	export const preloadFinish = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()

	useFrame(({ clock }) => {
		if (!$gltf || !$gltf.materials.FinishSign.map) return
		$gltf.materials.FinishSign.map.offset.x = clock.elapsedTime * 0.3
	})

	const { finishReached } = useTrackViewer()
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<!-- Finish Sensor -->
		<T.Group position.y={1.6}>
			<CollisionGroups groups={[3]}>
				<Collider
					type="static"
					shape="cuboid"
					args={[0.4, 1.5, 4]}
					on:sensorenter={() => {
						finishReached()
					}}
					sensor
				/>
			</CollisionGroups>
		</T.Group>

		<T.Group position.y={-0.25}>
			<Collider shape="cuboid" args={[5, 0.25, 5]} />
		</T.Group>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.Holds.geometry}
			material={$gltf.materials.Metall}
		/>
		<AutoColliders shape="cuboid">
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Roof.geometry}
				material={$gltf.materials.Metall}
			/>
		</AutoColliders>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.RoofBase.geometry}
			material={$gltf.materials['Gray Concretelike']}
			position={[0, 4.39, 0]}
			scale={[0.78, 1, 0.97]}
		/>
		<T.Group position={[0, 3.74, 0]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.Sign_1.geometry}
				material={$gltf.materials.FinishSign}
			/>
			<AutoColliders shape="cuboid">
				<T.Mesh
					castShadow
					receiveShadow
					geometry={$gltf.nodes.Sign_2.geometry}
					material={$gltf.materials.Metall}
				/>
			</AutoColliders>
		</T.Group>

		<!-- Stand colliders -->
		<T.Group position.y={2.36278} position.z={4.36758} rotation.x={-0.227438}>
			<Collider type="dynamic" shape="cuboid" args={[0.2, 1.925, 0.1]} />
		</T.Group>
		<T.Group position.y={2.36278} position.z={-4.36758} rotation.x={0.227438}>
			<Collider type="dynamic" shape="cuboid" args={[0.2, 1.925, 0.1]} />
		</T.Group>

		<!-- Stand Base Colliders -->
		<T.Group position.y={0.22} position.z={4.78}>
			<Collider type="dynamic" shape="cuboid" args={[1, 0.22, 0.225]} />
		</T.Group>
		<T.Group position.y={0.22} position.z={-4.78}>
			<Collider type="dynamic" shape="cuboid" args={[1, 0.22, 0.225]} />
		</T.Group>

		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.Stands.geometry}
			material={$gltf.materials['Metallic Dark']}
		/>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.StandsBase.geometry}
			material={$gltf.materials['Gray Concretelike']}
		/>

		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.Floor_1.geometry}
			material={$gltf.materials['Metallic Blue']}
		/>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.Floor_2.geometry}
			material={$gltf.materials['Gray Concretelike']}
		/>

		<slot {ref} />
	</T>
{/if}
