<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.9 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/EndlessRaceIntro/NonPhysicsBox/HalfBox.glb -u -i -t -s
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  type GLTFResult = {
    nodes: {
      HalfBox: THREE.Mesh
    }
    materials: {
      HalfBox: THREE.MeshStandardMaterial
    }
  }

  const gltf = suspend(useGltf<GLTFResult>('/HalfBox.glb'))
</script>

<T is={ref} dispose={false}>
  {#if $gltf}
    <T.Mesh castShadow receiveShadow geometry={$gltf.nodes.HalfBox.geometry} material={$gltf.materials.HalfBox} />
  {/if}

  <slot {ref} />
</T>
