<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.9 /Users/grischaerbe/Documents/Projects/2023/threltemania/src/components/TrackElements/Barriers/DoubleBarrier/DoubleBarrier.glb -u -i -t -s
-->
<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'
	import { useRefreshCollider } from '../../utils/useRefreshCollider'
	import { Collider } from '@threlte/rapier'

	export const ref = new Group()

	const suspend = useSuspense()

	type GLTFResult = {
		nodes: {
			DoubleBarrier: THREE.Mesh
		}
		materials: {}
	}

	const gltf = suspend(useGltf<GLTFResult>('/DoubleBarrier.glb'))

	const { refreshFns } = useRefreshCollider()
</script>

<T is={ref} dispose={false}>
	<T.Group position.y={0.3} position.z={4.75}>
		<Collider shape="cuboid" args={[5, 0.3, 0.3]} type="static" bind:refresh={refreshFns[0]} />
	</T.Group>
	<T.Group position.y={0.3} position.z={-4.75}>
		<Collider shape="cuboid" args={[5, 0.3, 0.3]} type="static" bind:refresh={refreshFns[1]} />
	</T.Group>

	{#if $gltf}
		<T.Mesh
			castShadow
			receiveShadow
			geometry={$gltf.nodes.DoubleBarrier.geometry}
			material={$gltf.nodes.DoubleBarrier.material}
		>
			<slot name="selection" />
		</T.Mesh>
	{/if}

	<slot {ref} />
</T>
