<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./barrier.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      Barrier: THREE.Mesh
    }
    materials: {}
  }

  const load = () => {
    return useGltf<GLTFResult>('/barrier-transformed.glb', { useDraco: true })
  }

  export const preloadBarrier = async () => {
    await load()
  }
</script>

<script lang="ts">
  export const ref = new Group()

  const gltf = load()
</script>

{#if $gltf}
  <T is={ref} dispose={false}>
    <T.Mesh castShadow receiveShadow geometry={$gltf.nodes.Barrier.geometry} material={$gltf.nodes.Barrier.material} />

    <slot {ref} />
  </T>
{/if}
