<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 ./TiltTransitionRightLong.glb -i -P -t -s -T
-->
<script context="module" lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import MeshCollider from '../../../utils/components/MeshCollider.svelte'

	type GLTFResult = {
		nodes: {
			TiltTransitionRightLong: THREE.Mesh
		}
		materials: {
			['Ramps.004']: THREE.MeshStandardMaterial
		}
	}

	const load = () => {
		return useGltf<GLTFResult>('/TiltTransitionRightLong-transformed.glb', { useDraco: true })
	}

	export const preloadTilttransitionrightlong = async () => {
		await load()
	}
</script>

<script lang="ts">
	export const ref = new Group()

	const gltf = load()
</script>

{#if $gltf}
	<T is={ref} dispose={false}>
		<MeshCollider>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={$gltf.nodes.TiltTransitionRightLong.geometry}
				material={$gltf.materials['Ramps.004']}
			>
				<slot name="selection" />
			</T.Mesh>
		</MeshCollider>

		<slot {ref} />
	</T>
{/if}
